name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run code linter
      run: npm run lint

    - name: Build project
      run: npm run build -- --base-href "/crypto-stock-screener/"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write

    steps:
      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/your-angular-app
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

